### ISSUE TITLE
A mistake in code and some questions about paper

### ISSUE THREAD

**Issue by hh23333** [qianwen96/UFDN-Reid#6]
Hi,
Thanks for sharing the code. It seems that the cls_token would not update through transform block at：
https://github.com/damo-cv/UFDN-Reid/blob/04da094371cbf4833e06f3ea30fb28f7e904555f/modeling/backbone/PDecouple_resnet.py#L229-L230
Such that, no matter how many layers are set, the results will be the same with using 1 layer. 
I also have some questions about code and paper,
1. I notice that when using model with pd, you use unshared parameters for global and local branch. My questions is, have you ever try to use the shared features. Furthermore,  have you ever do the ablation study on only add unshared classifier on these local features extracted by unshared module parameters?
2. As described in Sec3.2 of your paper, F^i_p is frozen during traing, I did not find this operation in the code. How did you do that?
3. I notice that you use a learnable parameter gamma to control the learning of attention block, is it the rezero trick for training? Is it critical for network training? @michuanhaohao

Best Regard!

**Comment by hh23333** [comment]
https://github.com/damo-cv/UFDN-Reid/blob/04da094371cbf4833e06f3ea30fb28f7e904555f/modeling/backbone/PDecouple_resnet.py#L229-L230

**Comment by hh23333** [comment]
Hello,
I’m still waiting for your response to my issue. I appreciate your work on this project and I hope you can help me solve my problem. I noticed that you have replied to other issues after mine, so I wonder if you have missed mine or if you need more information from me. Please let me know if you have any updates or questions. Thank you for your time and attention. @qianwen96

**Comment by qianwen96** [comment]
Thank you for bringing up this issue, we have paid attention to your question. As we have been busy with other deadlines recently, the reply has been slow. The errors mentioned here were due to the uploading of some old versions of files, which will be updated.  Here are the response to your above question：
1）A bug exists in our code which leads to the cls_token would not update， and all our experiments are based on 1 layer transformer-based decode head. We have corrected this bug, and experiments on 776, which get 80.7%（Swin-tiny backbone）and 81.6%（Res50 backbone）with a 2-layer transformer-based decode head.
![image](https://user-images.githubusercontent.com/39210807/229757554-a6c7d29f-7b0b-4661-8038-af51610e8433.png)

![image](https://user-images.githubusercontent.com/39210807/229757345-abb659f8-52a0-45ce-afc5-50b0fd42eff3.png)

2) Actually, the global and local branches share the first two blocks and then different parameters for the next two blocks for learning different and diverse information.
3) As shown in Fig.3 of our paper, and 229-230 in [PDecouple_resnet.py](https://github.com/damo-cv/UFDN-Reid/blob/04da094371cbf4833e06f3ea30fb28f7e904555f/modeling/backbone/PDecouple_resnet.py#L229-L230), the features are not updated, and thus we called F^i_p is frozen during training.
4) Actually, the learnable parameter gamma is a trick that sometimes can lead to a little performance improvement.
